### ISSUE TITLE
List of proposed Features

### ISSUE THREAD

**Issue by Muirrum** [wpi-25/bot#1]
- [x] XKCD
- [ ] Dumb triggers #4 
- [ ] Poll bot #5 
- [ ] Embed creator
   - [ ] Custom social media embed creator #6 
- [x] Auto-update member count

Potentially more to come

**Comment by i-am-gizm0** [comment]
- [ ] Auto-update member count

**Comment by EarlJr53** [comment]
Do we actually use this issue anymore? Do we want to start referencing other enhancements here?
