### ISSUE TITLE
Giving out and replacing level roles

### ISSUE THREAD

**Issue by EarlJr53** [wpi-25/bot#27]
I would like the bot to be able to give out roles based on a member's level. Currently, I have roles for Level 1, and then multiples of 5. We can add more if we'd like. The purpose is to keep the most active people visible on the sidebar. Essentially, I'd like the bot to give "@Level 5" when someone reaches level 5, and take away their previous Level role. If possible, it would also be nice to have the bot give out the roles to everyone who doesn't have them right now, as doing that manually would be a pain.

**Comment by samollari** [comment]
How do we want to implement this? Does *at every new level, check for a role that matches `Level ${n}`* make sense?
