### ISSUE TITLE
DM new members on initial join

### ISSUE THREAD

**Issue by EarlJr53** [wpi-25/bot#63]
Similar to #62 except for newly joining members. When someone first joins the server, send them a DM explaining how to get their roles and gain access to the server.

**Comment by EarlJr53** [comment]
I *think* I already set this up inside CarlBot (or at least I *can* do that), so we don't really need to.

**Comment by Muirrum** [comment]
Yep, you can change the welcome message to go to DMs

**Comment by EarlJr53** [comment]
> Yep, you can change the welcome message to go to DMs

Yep! I just checked and I had already done that. I outdo myself sometimes.
