### ISSUE TITLE
Add ability to create and track invites

### ISSUE THREAD

**Issue by EarlJr53** [wpi-25/bot#93]
We want to be able to send out some permalink invites to the main server and some other places. However, you can only manually create 1 permalink invite to each channel at a time (and we need all of ours to point to #rules). The main server's GompeiBot has the ability to create unique permalink invites and store descriptions alongside each (i.e. where we are sending it, allowing us to track where new members come from). This will be useful for normal day-to-day activity as well as if we encounter another raid. I would probably say we should talk to Sam C when he has some time and/or look through the GompeiBot code to see how he did it.

**Comment by samollari** [comment]
IIRC to figure out which invite was used with a particular join, it keeps a DB of current invites and their uses and compares the counts for each invite to find a difference

**Comment by Muirrum** [comment]
for reference: 

- https://github.com/SamuelCurrid/Gompei-Bot/blob/824b0601429f978c066e2e98c471cb386a780e5c/cogs/Administration.py#L944 (creating invites
- https://github.com/SamuelCurrid/Gompei-Bot/blob/4c1bd803fcd84ab9c6d0f7ea8dfe9ee8d08ccc77/cogs/Logging.py#L155 (adding notes)
- https://github.com/SamuelCurrid/Gompei-Bot/blob/4c1bd803fcd84ab9c6d0f7ea8dfe9ee8d08ccc77/cogs/Logging.py#L714 (invite tracking)

**Comment by samollari** [comment]
Will be replaced/implemented by [Scribe](https://github.com/wpi-25/scribe)
